name: team_mas404
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  confetti: ^0.6.0
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  cloud_firestore: ^3.1.7
  math_expressions: ^2.3.0
  google_sign_in: ^5.2.4
  #firebase_auth: ^3.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0
  
flutter:

  uses-material-design: true
  
  # assets:
  #   - images/
  fonts:
    - family: QwitcherGrypen
      fonts:
        - asset: fonts/QwitcherGrypen-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

